/**
 * McLeod TMS REST API Types
 * Based on McLeod REST API documentation
 *
 * IMPORTANT: McLeod uses REST (NOT SOAP). All endpoints are under /ws/api
 */

/**
 * McLeod RowCustomer structure as returned by GET /customers/new
 * Only set fields that exist in the actual response - do not invent fields
 */
export interface RowCustomer {
  // Primary identifier - auto-generated by McLeod or set by us
  id?: string;

  // Company information
  name: string;                    // Legal company name (required)
  name2?: string;                  // DBA / alternate name
  address1: string;                // Street address (required)
  address2?: string;               // Street address line 2
  city: string;                    // City (required)
  state_id: string;                // 2-letter state code (required) - NOTE: McLeod uses state_id, not state
  zip_code: string;                // Postal code (required)
  country_code?: string;           // Country code (default: USA)

  // Contact information
  phone1?: string;                 // Primary phone
  phone2?: string;                 // Secondary phone
  fax?: string;                    // Fax number
  email?: string;                  // Primary email

  // Tax/regulatory
  federal_id?: string;             // EIN/Tax ID (9 digits)
  ic_number?: string;              // Interstate Commerce (MC) number

  // Status and classification
  status?: string;                 // Customer status (A=Active, I=Inactive)
  customer_type?: string;          // Customer type/category

  // Credit
  credit_limit?: number;           // Credit limit in dollars
  credit_status?: string;          // Credit status code

  // Payment
  terms?: string;                  // Payment terms code

  // Assignment
  salesperson_id?: string;         // Salesperson code

  // Primary contact fields (embedded in customer)
  contact_name?: string;           // Primary contact name

  // Audit fields
  entered_user_id?: string;        // User who created
  entered_date?: string;           // Date created

  // Allow additional fields from McLeod that we don't explicitly type
  [key: string]: unknown;
}

/**
 * McLeod RowContact structure for ContactService
 * Per McLeod API docs: PUT /contacts/create
 */
export interface RowContact {
  // Required fields
  __type?: string;                 // 'contact'
  company_id?: string;             // 'TMS'
  id?: string;                     // Contact ID (auto-generated, max 32)
  parent_row_id: string;           // Customer ID (max 8)
  parent_row_type?: string;        // 'C' for customer contact (max 1)
  row_type?: 'C';                  // Legacy - use parent_row_type

  // Contact info (per API spec)
  name?: string;                   // Full name (max 40)
  contact_name?: string;           // Contact name (max 40)
  email?: string;                  // Email (max 60)
  phone?: string;                  // Phone (max 20)
  mobile_phone?: string;           // Mobile phone (max 20)
  fax?: string;                    // Fax (max 20)
  title?: string;                  // Title (max 30)

  // Classification flags (Y/N)
  is_active?: string;              // Active flag (max 1)
  payable_contact?: string;        // AP contact flag (max 1)
  detention_contact?: string;      // Detention contact (max 1)
  terms_contact?: string;          // Terms contact (max 1)

  // Other fields
  sequence?: number;               // Sequence number
  comments?: string;               // Comments (max 254)

  // Allow additional fields
  [key: string]: unknown;
}

/**
 * McLeod RowComment structure for CommentService
 */
export interface RowComment {
  id?: string;
  row_type: 'C';                   // C = Customer comment
  parent_row_id: string;           // Customer ID
  comment_type?: string;           // Comment type code
  comment: string;                 // Comment text
  entered_user_id?: string;        // User who entered
  entered_date?: string;           // Date entered

  [key: string]: unknown;
}

/**
 * Customer search parameters for GET /customers/search
 * Use prefixes like customer.* or no prefix per docs
 */
export interface CustomerSearchParams {
  // NOTE: federal_id field not yet verified - do not use for matching until confirmed
  // 'customer.federal_id'?: string;
  'customer.name'?: string;
  'customer.city'?: string;
  'customer.state_id'?: string;  // NOTE: McLeod uses state_id, not state
  'customer.zip_code'?: string;
  'customer.id'?: string;
  // Allow string params for query building
  [key: string]: string | undefined;
}

/**
 * Search results wrapper
 */
export interface CustomerSearchResult {
  customers: RowCustomer[];
  totalCount: number;
  hasMore: boolean;
}

/**
 * Token response from POST /users/login
 */
export interface LoginResponse {
  token: string;
  expiresIn?: number;
}

/**
 * Legacy types kept for backward compatibility
 */
export interface McLeodCustomer {
  id: string;
  name: string;
  dba_name?: string;
  address1: string;
  address2?: string;
  city: string;
  state_id: string;  // NOTE: McLeod uses state_id, not state
  zip_code: string;
  phone?: string;
  phone2?: string;
  fax?: string;
  email?: string;
  federal_id?: string;
  mc_number?: string;
  dot_number?: string;
  status: string;
  category?: string;
  customer_type?: string;
  credit_limit: number;
  credit_status?: string;
  credit_approved?: boolean;
  credit_approved_by?: string;
  credit_approved_date?: string;
  payment_terms?: string;
  payment_method?: string;
  salesperson_id?: string;
  contact_name?: string;
  contact_email?: string;
  contact_phone?: string;
  ap_contact_name?: string;
  ap_email?: string;
  ap_phone?: string;
  notes?: string;
  comments?: string;
  created_date?: string;
  created_by?: string;
  modified_date?: string;
  modified_by?: string;
  custom_field_1?: string;
  custom_field_2?: string;
  custom_field_3?: string;
}

export interface McLeodSearchCriteria {
  id?: string;
  name?: string;
  // federal_id?: string;  // Not yet verified - do not use until confirmed
  city?: string;
  state_id?: string;  // NOTE: McLeod uses state_id, not state
  zip_code?: string;
  phone?: string;
  email?: string;
  status?: string;
}

export interface McLeodSearchResult {
  customers: McLeodCustomer[];
  totalCount: number;
  hasMore: boolean;
}

export interface McLeodDocument {
  document_id?: string;
  entity_type: 'CUSTOMER' | 'ORDER' | 'LOAD';
  entity_id: string;
  document_type: string;
  filename: string;
  content_type: string;
  content?: string;
  description?: string;
  uploaded_date?: string;
  uploaded_by?: string;
}

export interface McLeodContact {
  contact_id?: string;
  customer_id: string;
  contact_type: 'PRIMARY' | 'LOGISTICS' | 'ACCOUNTS_PAYABLE' | 'BILLING' | 'OTHER';
  first_name: string;
  last_name: string;
  title?: string;
  email?: string;
  phone?: string;
  fax?: string;
  is_primary?: boolean;
}

/**
 * McLeod API Response wrapper
 */
export interface McLeodApiResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: {
    code: string;
    message: string;
    details?: string;
  };
}

/**
 * Valid credit status codes for this McLeod instance
 * - A = Approved (credit approved, can extend terms)
 * - D = Denied (credit denied, do not extend terms)
 * - T = Tentative (pending approval, do not extend terms)
 */
export const MCLEOD_CREDIT_STATUS = {
  APPROVED: 'A',
  DENIED: 'D',
  TENTATIVE: 'T',
} as const;

/**
 * Credit status for new customers from Jotform
 * Use TENTATIVE until billing runs credit check
 */
export const JOTFORM_DEFAULT_CREDIT_STATUS = MCLEOD_CREDIT_STATUS.TENTATIVE;

/**
 * Valid customer status codes
 */
export const MCLEOD_CUSTOMER_STATUS = {
  ACTIVE: 'A',
  INACTIVE: 'I',
} as const;

/**
 * Payment terms mapping
 */
export const MCLEOD_PAYMENT_TERMS: Record<string, string> = {
  'Net 15': 'NET15',
  'Net 30': 'NET30',
  'Net 45': 'NET45',
  'Net 60': 'NET60',
  'Due on Receipt': 'DOR',
  'Cash on Delivery': 'COD',
  'Prepaid': 'PREPAID',
};
